services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: invoices_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - invoices_network
    depends_on:
      - postgres

  nginx:
    image: nginx:alpine
    container_name: invoices_nginx
    restart: unless-stopped
    ports:
      - "7778:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - invoices_network
    depends_on:
      - app

  postgres:
    image: postgres:16-alpine
    container_name: invoices_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: invoices_db
      POSTGRES_USER: invoices_user
      POSTGRES_PASSWORD: invoices_password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - invoices_network
    ports:
      - "5434:5432"

networks:
  invoices_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local

